package MessageHandlers.Statuses.administration;

import MessageHandlers.Statuses.Statuses;

public enum OwnerStatuses implements Statuses{
    ADD_PRODUCT_GENDER,
    ADD_PRODUCT_SEASON,
    ADD_PRODUCT_TYPE,
    ADD_PRODUCT_TITLE,
    ADD_PRODUCT_IMAGE,
    ADD_PRODUCT_DESCRIPTION,
    ADD_PRODUCT_SIZE,
    ADD_PRODUCT_PRICE,

    EDIT_PRODUCT_GENDER,
    EDIT_PRODUCT_SEASON,
    EDIT_PRODUCT_TYPE,
    EDIT_PRODUCT_TITLE,
    EDIT_PRODUCT_IMAGE,
    EDIT_PRODUCT_DESCRIPTION,
    EDIT_PRODUCT_SIZE,
    EDIT_PRODUCT_PRICE,

    SET_RECOMMENDATIONS
}
